// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ant-spin-container': string;
  'ant-spin-nested-loading': string;
  footer: string;
  form: string;
  logo: string;
}
export const cssExports: CssExports;
export default cssExports;
